INSERT INTO ACTIVIDADES (NOMBRE_ACTIVIDAD, OBLIGATORIO, TIPO_ACTIVIDAD, ESTATUS, AGREGADO_POR, FECHA_CREACION, SW_HORARIO)
VALUES ('BIBLIOTECA',   'S', 'B', 'S', 'ADMIN', NOW(), 'N'),
       ('SALA DE CÓMPUTO',     'S', 'S', 'S', 'ADMIN', NOW(), 'S'),
       ('CLUB DE AJEDREZ',     'N', 'EX', 'S', 'ADMIN', NOW(), 'S'),
       ('EDUCACIÓN FÍSICA',    'N', 'EX', 'S', 'ADMIN', NOW(), 'S'),
       ('RONDALLA',            'N', 'EX', 'S', 'ADMIN', NOW(), 'S'),
       ('CLUB DE LECTURA',     'N', 'EX', 'S', 'ADMIN', NOW(), 'S'),
       ('CLUB DE CINE',        'N', 'EX', 'S', 'ADMIN', NOW(), 'S'),
       ('TAEKWONDO',           'N', 'EX', 'S', 'ADMIN', NOW(), 'S');

INSERT INTO ROLES (NOMBRE_ROL, ESTATUS,AGREGADO_POR, FECHA_CREACION, ACTUALIZADO_POR, FECHA_ACTUALIZACION) VALUES ('ADMINISTRADOR','S','ADMIN', '2019-10-04 15:05:13', null, null);
INSERT INTO ROLES (NOMBRE_ROL, ESTATUS,AGREGADO_POR, FECHA_CREACION, ACTUALIZADO_POR, FECHA_ACTUALIZACION) VALUES ('ENCARGADO', 'S','ADMIN', '2019-10-04 15:05:13', null, null);
INSERT INTO ROLES (NOMBRE_ROL, ESTATUS,AGREGADO_POR, FECHA_CREACION, ACTUALIZADO_POR, FECHA_ACTUALIZACION) VALUES ('ALUMNO', 'S','ADMIN', '2019-10-04 15:05:13', null, null);


INSERT INTO USUARIOS (NOMBRES, APE_PATERNO, APE_MATERNO, ID_ROL, USERNAME, PASSWORD, ESTATUS, AGREGADO_POR,
                      FECHA_CREACION)
VALUES ('LEONARDO', 'MARCOS', 'SANTIAGO', 1, 'marcossleo2@gmail.com', '****', 'S', 'ADMIN', NOW()),
       ('LUIS ÁNGEL', 'PEREZ', 'HERRERA', 2, 'luis@gmail.com', '****', 'S', 'ADMIN', NOW())
;

INSERT INTO HORARIO_ACTIVIDAD (ID_ACTIVIDAD, HORA, AM_PM, NUMERO_ALUMNOS, ID_USUARIO, CVE_PERIODO, DESC_PERIDODO, ESTATUS,
                               AGREGADO_POR, FECHA_CREACION)
VALUES (3, '07', 'PM', 20, 1, '1819B', 'SEM-MAR/19-JUN/19','S', 'ADMIN', NOW()),
       (3, '08', 'PM', 20, 2, '1819B', 'SEM-MAR/19-JUN/19', 'S', 'ADMIN', NOW()),
       (4, '07', 'AM', 30, 1, '1819B', 'SEM-MAR/19-JUN/19', 'S', 'ADMIN', NOW()),
       (4, '08', 'AM', 30, 2, '1819B', 'SEM-MAR/19-JUN/19', 'S', 'ADMIN', NOW()),
       (5, '05', 'PM', 40, 1, '1819B', 'SEM-MAR/19-JUN/19', 'S', 'ADMIN', NOW()),
       (6, '07', 'AM', 50, 2, '1819B', 'SEM-MAR/19-JUN/19', 'S', 'ADMIN', NOW()),
       (2, '05', 'PM', 40, 2, '1819B', 'SEM-MAR/19-JUN/19', 'S', 'ADMIN', NOW());


INSERT INTO PARCIALES (DESC_PARCIAL, AGREGADO_POR, FECHA_CREACION)
VALUES ('1er Parcial', 'ADMIN',  NOW()),
       ('2do Parcial', 'ADMIN',  NOW()),
       ('3er Parcial', 'ADMIN',  NOW());

INSERT INTO PARCIAL_PERIODO (ID_PARCIAL, PARCIAL, PARCIAL_ACTUAL, FECHA_INICIO, FECHA_FIN, CVE_PERIODO, DESC_PERIODO, TOTAL_HORAS_BIBLIOTECA, TOTAL_ASISTENCIA_SALA, AGREGADO_POR, FECHA_CREACION, ACTUALIZADO_POR, FECHA_ACTUALIZACION) VALUES (1, 1, 'S', '2012-10-01', '2013-02-15', '1213A', 'SEM-oct/12-feb/13', 30, 45, 'admin', '2020-02-23 21:51:50', null, null);



INSERT INTO MENU (ID_PADRE, NOMBRE, ICON, URL, AGREGADO_POR, FECHA_CREACION)
VALUES
    --  menu principal
    (1, 'Configuración', 'mdi mdi-settings', 'configuracion', 'ADMIN', NOW()),
    (2, 'Alumnos', 'mdi mdi-account', 'alumnos', 'ADMIN', NOW()),
    (3, 'Reporte Actividad', 'mdi mdi-upload', 'reporte-actividades', 'ADMIN', NOW()),
    (4, 'Catálogos', 'mdi mdi-book', 'catalogos', 'ADMIN', NOW()),
    (5, 'Seguridad', 'mdi mdi-lock', 'seguridad', 'ADMIN', NOW()),
    -- submenus
    (1, 'Periodo', null, 'periodo', 'ADMIN', NOW()),
    (1, 'Horario Actividades', null, 'horario-actividades', 'ADMIN', NOW()),

    (2, 'Carga Alumnos Periodo', null, 'admin', 'ADMIN', NOW()),
    (2, 'Detalle Alumno', null, 'detalle', 'ADMIN', NOW()),
    (2, 'Registro en Actividad', null, 'inscripcion-actividad', 'ADMIN', NOW()),
    (2, 'Inscripciones', null, 'administrar-inscripciones', 'ADMIN', NOW()),

    (3, 'Registro Asistencia Sala de Cómputo', null, 'asistencia-sala', 'ADMIN', NOW()),
    (3, 'Registro % Actividades', null, 'registro-porcentaje-actividad', 'ADMIN', NOW()),
    (3, 'Carga Horas Biblioteca', null, 'carga-hrs-biblioteca', 'ADMIN', NOW()),
    (3, 'Carga Horas Sala de Cómputo', null, 'carga-hrs-sala-computo', 'ADMIN', NOW()),
    (3, 'Reporte detallado', null, 'detallado', 'ADMIN', NOW()),

    (4, 'Licenciaturas', null, 'licenciaturas', 'ADMIN', NOW()),
    (4, 'Grupos', null, 'grupos', 'ADMIN', NOW()),
    (4, 'Actividades', null, 'actividades', 'ADMIN', NOW()),

    (5, 'Usuarios', null, 'usuarios', 'ADMIN', NOW())
;

-- ASIGNACION DE MENU A ROL
INSERT INTO MENU_ROL (ID_MENU, ID_ROL, AGREGADO_POR, FECHA_CREACION) VALUES (6, 1, 'ADMIN', NOW());
INSERT INTO MENU_ROL (ID_MENU, ID_ROL, AGREGADO_POR, FECHA_CREACION) VALUES (7, 1, 'ADMIN', NOW());
INSERT INTO MENU_ROL (ID_MENU, ID_ROL, AGREGADO_POR, FECHA_CREACION) VALUES (8, 1, 'ADMIN', NOW());
INSERT INTO MENU_ROL (ID_MENU, ID_ROL, AGREGADO_POR, FECHA_CREACION) VALUES (11, 1, 'ADMIN', NOW());
INSERT INTO MENU_ROL (ID_MENU, ID_ROL, AGREGADO_POR, FECHA_CREACION) VALUES (12, 1, 'ADMIN', NOW());
INSERT INTO MENU_ROL (ID_MENU, ID_ROL, AGREGADO_POR, FECHA_CREACION) VALUES (13, 1, 'ADMIN', NOW());
INSERT INTO MENU_ROL (ID_MENU, ID_ROL, AGREGADO_POR, FECHA_CREACION) VALUES (14, 1, 'ADMIN', NOW());
INSERT INTO MENU_ROL (ID_MENU, ID_ROL, AGREGADO_POR, FECHA_CREACION) VALUES (15, 1, 'ADMIN', NOW());
INSERT INTO MENU_ROL (ID_MENU, ID_ROL, AGREGADO_POR, FECHA_CREACION) VALUES (16, 1, 'ADMIN', NOW());
INSERT INTO MENU_ROL (ID_MENU, ID_ROL, AGREGADO_POR, FECHA_CREACION) VALUES (17, 1, 'ADMIN', NOW());
INSERT INTO MENU_ROL (ID_MENU, ID_ROL, AGREGADO_POR, FECHA_CREACION) VALUES (18, 1, 'ADMIN', NOW());
INSERT INTO MENU_ROL (ID_MENU, ID_ROL, AGREGADO_POR, FECHA_CREACION) VALUES (19, 1, 'ADMIN', NOW());
INSERT INTO MENU_ROL (ID_MENU, ID_ROL, AGREGADO_POR, FECHA_CREACION) VALUES (20, 1, 'ADMIN', NOW());
INSERT INTO MENU_ROL (ID_MENU, ID_ROL, AGREGADO_POR, FECHA_CREACION) VALUES (6, 2, 'ADMIN', NOW());
INSERT INTO MENU_ROL (ID_MENU, ID_ROL, AGREGADO_POR, FECHA_CREACION) VALUES (7, 2, 'ADMIN', NOW());
INSERT INTO MENU_ROL (ID_MENU, ID_ROL, AGREGADO_POR, FECHA_CREACION) VALUES (8, 2, 'ADMIN', NOW());
INSERT INTO MENU_ROL (ID_MENU, ID_ROL, AGREGADO_POR, FECHA_CREACION) VALUES (11, 2, 'ADMIN', NOW());
INSERT INTO MENU_ROL (ID_MENU, ID_ROL, AGREGADO_POR, FECHA_CREACION) VALUES (12, 2, 'ADMIN', NOW());
INSERT INTO MENU_ROL (ID_MENU, ID_ROL, AGREGADO_POR, FECHA_CREACION) VALUES (13, 2, 'ADMIN', NOW());
INSERT INTO MENU_ROL (ID_MENU, ID_ROL, AGREGADO_POR, FECHA_CREACION) VALUES (14, 2, 'ADMIN', NOW());
INSERT INTO MENU_ROL (ID_MENU, ID_ROL, AGREGADO_POR, FECHA_CREACION) VALUES (15, 2, 'ADMIN', NOW());
INSERT INTO MENU_ROL (ID_MENU, ID_ROL, AGREGADO_POR, FECHA_CREACION) VALUES (16, 2, 'ADMIN', NOW());
INSERT INTO MENU_ROL (ID_MENU, ID_ROL, AGREGADO_POR, FECHA_CREACION) VALUES (17, 2, 'ADMIN', NOW());
INSERT INTO MENU_ROL (ID_MENU, ID_ROL, AGREGADO_POR, FECHA_CREACION) VALUES (18, 2, 'ADMIN', NOW());
INSERT INTO MENU_ROL (ID_MENU, ID_ROL, AGREGADO_POR, FECHA_CREACION) VALUES (19, 2, 'ADMIN', NOW());
INSERT INTO MENU_ROL (ID_MENU, ID_ROL, AGREGADO_POR, FECHA_CREACION) VALUES (20, 2, 'ADMIN', NOW());
INSERT INTO MENU_ROL (ID_MENU, ID_ROL, AGREGADO_POR, FECHA_CREACION) VALUES (9, 3, 'ADMIN', NOW());
INSERT INTO MENU_ROL (ID_MENU, ID_ROL, AGREGADO_POR, FECHA_CREACION) VALUES (10, 3, 'ADMIN', NOW());
INSERT INTO MENU_ROL (ID_MENU, ID_ROL, AGREGADO_POR, FECHA_CREACION) VALUES (16, 3, 'ADMIN', NOW());
INSERT INTO MENU_ROL (ID_MENU, ID_ROL, AGREGADO_POR, FECHA_CREACION) VALUES (10, 1, 'ADMIN', NOW());
INSERT INTO MENU_ROL (ID_MENU, ID_ROL, AGREGADO_POR, FECHA_CREACION) VALUES (10, 2, 'ADMIN', NOW());
UPDATE MENU SET ESTATUS = 'N' WHERE ID_MENU = 15;
UPDATE MENU SET ESTATUS = 'N' WHERE ID_MENU = 13;

update USUARIOS U set PASSWORD = sha2(concat('4^%m@=C*&c#L+%', 'prueba', 'U$|2AT>30!'), 224) where ID_USUARIO = 1;
update USUARIOS U set PASSWORD = sha2(concat('4^%m@=C*&c#L+%', 'prueba', 'U$|2AT>30!'), 224) where ID_USUARIO = 2;


-- SELECT * FROM ALUMNOS where MATRICULA = '2012060169';
/*INSERT INTO ALUMNOS (MATRICULA, CURP, NOMBRES, APE_PATERNO, APE_MATERNO, ESTATUS, AGREGADO_POR, FECHA_CREACION)
VALUES('2012060169', 'KDASHDJKHASK', 'LEO', 'PRUEBA', '', 'S', 'ADMIN', NOW());

INSERT INTO ALUMNOS_DAT_PERIODO ( MATRICULA, CVE_GRUPO, DESC_GRUPO, CVE_LICENCIATURA, DESC_LICENCIATURA, CVE_PERIODO, DESC_PERIDODO)
VALUES ('2012060169', '206B','206B','06','LICENCIATURA EN INFORMÁTICA','1819B', 'SEM-MAR/19-JUN/19');*/


INSERT INTO `ALUMNOS` (`MATRICULA`, `CODIGO_RFID`, `CURP`, `NOMBRES`, `APE_PATERNO`, `APE_MATERNO`, `ESTATUS`, `AGREGADO_POR`, `FECHA_CREACION`, `ACTUALIZADO_POR`, `FECHA_ACTUALIZACION`) VALUES ('2012060169', '2012060169', 'masl', 'leo', 'ms', 'stg', 'S', 'ADMIn', '2020-04-18 16:48:37', null, null)
INSERT INTO `ALUMNOS_DAT_PERIODO` (`MATRICULA`, `CVE_GRUPO`, `DESC_GRUPO`, `CVE_LICENCIATURA`, `DESC_LICENCIATURA`, `CVE_PERIODO`, `DESC_PERIDODO`, `ESTATUS`) VALUES ('2012060169', '201', '201', '01B', 'LICENCIATURA EN ADMINISTRACIÓN MUNICIPAL 2015', '1819B', 'SEM-MAR/19-JUN/19', 'S');