/*
SELECT * FROM ACTIVIDADES;

SELECT A.ID_ACTIVIDAD, A.NOMBRE_ACTIVIDAD, DE.HORA, DE.AM_PM, DE.NUMERO_ALUMNOS, DE.ESTATUS
FROM ACTIVIDADES A, DETALLE_ACTIVIDADES DE
WHERE A.ID_ACTIVIDAD = DE.ID_ACTIVIDAD
  AND A.ESTATUS = 'S'
  AND A.ID_ACTIVIDAD =3;

*/