/*

    -- Actividad alumno
SELECT C.ID_CICLO_ESCOLAR, C.DESCRIPCION_CICLO, C.PERIODO_ACTUAL,
       A.ID_ACTIVIDAD, A.NOMBRE_ACTIVIDAD,
       H.ID_HORARIO_ACTIVIDAD, H.HORA, H.AM_PM,
       AL.ID_ALUMNO, AL.ID_GRUPO,
       ALU.MATRICULA, ALU.NOMBRES, ALU.APE_PATERNO, ALU.APE_MATERNO
FROM CICLO_ESCOLAR C, HORARIO_ACTIVIDAD H, ACTIVIDADES A, ACTIVIDAD_ALUMNO AL, ALUMNOS ALU
WHERE C.PERIODO_ACTUAL = 'S'
  AND H.ESTATUS = 'S'
  AND C.ESTATUS = 'S'
  AND A.ESTATUS = 'S'
  AND ALU.ESTATUS = 'S'
  AND C.ID_CICLO_ESCOLAR = H.ID_CICLO_ESCOLAR
  AND H.ID_ACTIVIDAD = A.ID_ACTIVIDAD
  AND H.ID_HORARIO_ACTIVIDAD = AL.ID_ACTIVIDAD
  AND ALU.ID_ALUMNO = AL.ID_ALUMNO

*/